### ISSUE TITLE
Fail to install/run with yarn 0.17.x

### ISSUE THREAD

**Issue by IvanSanchez** [gobblejs/gobble#127]
I'm trying to get some of my workflows out of `npm` and into [`yarn`](http://www.yarnpkg.com). Everything was working fine with yarn <= v0.16.x, but things started to break with the release of yarn 0.17.x.

Right now trying to run `gobble-cli` fails with:

```
ivan:/tmp/example$ yarn --version
0.17.2

ivan:/tmp/example$ yarn add gobble-cli
yarn add v0.17.2
warning gobble-example@0.1.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
└─ gobble-cli@0.7.0
warning gobble-example@0.1.0: No license field
Done in 3.24s.

ivan:/tmp/example$ node_modules/.bin/gobble 
module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Release/pathwatcher.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/example/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/tmp/example/node_modules/pathwatcher/lib/main.js:218:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

I've had a look at the [changelog for Yarn 0.17.0](https://github.com/yarnpkg/yarn/releases/tag/v0.17.0), but there are too many things there to know what exactly changed the behaviour.

**Comment by IvanSanchez** [comment]
This might be already fixed by https://github.com/gobblejs/gobble/commit/efa4034b86b17b8c880b6669a9d2760c366f9d3c , as it changes back the file watching lib to chokidar once more.

@TrySound Should we try releasing this?

**Comment by IvanSanchez** [comment]
Cannot be reproduced anymore in my environment, as yarn has new versions that Just Work™
